config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :insurances
  resources :contacts, only: [:new, :create]
  resources :about, only: [:index]
  resources :customer_service

  resources :quotes, only: [:index, :create]
  namespace :insurance_leads do
    resources :current_auto_insurance_policies, only: [:show]
    resources :current_home_insurance_policies, only: [:show]
  end
  get 'welcome/index'
  root 'welcome#index'

  get '*path' => redirect('/')
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
	extend FriendlyId
  friendly_id :title, use: :slugged

  has_attached_file :image, styles: {  xlarge: "1260x1260>", large: "600x600>", medium: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
	before_action :find_insurance, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@insurances = Insurance.all.order("created_at desc")
	end

	def new
		@insurance = Insurance.new
	end
		
	def create
		@insurance = Insurance.new insurance_params

		if @insurance.save
			redirect_to @insurance, notice: "Success."
		else
			render 'new'
		end
	end

	def show
		@insurances = Insurance.all.order('random()')
		@posts = Post.all.order('random()').paginate(page: params[:page], per_page: 6)
	end

	def edit
	end

	def update
		if @insurance.update(insurance_params)
			redirect_to @insurance, notice: "Success."
		else
			render 'edit'
		end
	end

	def destroy
		@insurance.destroy
		redirect_to insurances_path
	end

	private

	def insurance_params
		params.require(:insurance).permit(:title, :description, :link, :image, :slug)
	end

	def find_insurance
		@insurance = Insurance.friendly.find(params[:id])
	end

end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/views/insurances/_form.html.erb
<div class="form">
	<%= form_for @insurance, html: { multipart: true } do |f| %>
		<% if @insurance.errors.any? %>
			<h2> <%= pluralize(@insurance.errors.count, "error") %> Prevented this insurance from saving: </h2>
			<ul>
				<% @insurance.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
		<%= f.label :image %>
		<%= f.file_field :image %>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<%= f.label 'subheader' %>
		<%= f.text_field :link %>
		<%= f.label :description %>
		<%= f.text_area :description %>
		<%= f.submit 'Save', class: 'button'  %>
	<% end %>
</div>

app/views/insurances/_hero.html.erb
<div class="image-gradient-dynamic">
	<%= image_tag @insurance.image.url(:large) %>
	<div class="copy">
    <h2 class="welcome-text animated bounce fadeInDown"><span class="db"><strong><%= @insurance.title %></strong></span></h2>
  </div>
</div>

app/views/insurances/edit.html.erb
<article class="type-system-serif">
	<section class="wrapper">
		<h1 id="form_title">Edit Insurance Type</h1>
		<%= render 'form' %>
	</section>
</article>

app/views/insurances/index.html.erb
<%= render "hero_index" %>
<article class="wrapper">
	<div class="content_list">
		<% @insurances.each do |insurance| %>
			<%= link_to insurance, :class => 'content_list_item border-radius' do%>
				<div class="image_wrapper">	
					<%= image_tag insurance.image.url(:large) %>
					<!-- <%= image_tag('bg/elderly-couple.png') %> -->
				</div>
				<h2><%= insurance.title %></h2>
				<p><%= truncate(insurance.description, :length => 145) %></p>
			<% end %>
		<% end %>
	</div>
	<%= render "sidebar" %>
</article>

app/views/insurances/new.html.erb
<%= render 'form' %>

app/views/insurances/show.html.erb
<%= render "hero" %>
<article class="wrapper type-system-traditional">
	<div class="skinny_wrapper skinny_wrapper--article pull_up">
  <h2> <%= @insurance.link%> </h2>
	<%= markdown @insurance.description %>
	<div id="admin_links">
		<% if user_signed_in? %>
			<%= link_to "Edit", edit_insurance_path(@insurance) %>
			<%= link_to "Delete", insurance_path(@insurance), method: :delete, data: { confirm: "Are you sure?" } %>
		<% end %>
	</div>
</div>
	<%= render "sidebar" %>
</article>