config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :insurances
  resources :contacts, only: [:new, :create]
  resources :about, only: [:index]
  resources :customer_service

  resources :quotes, only: [:index, :create]
  namespace :insurance_leads do
    resources :current_auto_insurance_policies, only: [:show]
    resources :current_home_insurance_policies, only: [:show]
  end
  get 'welcome/index'
  root 'welcome#index'

  get '*path' => redirect('/')
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  	@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page:5)
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_grid_objects.html.erb
<div class="grid-items-lines">
  <% @insurance_grid.each_with_index do |insurance, index| %>
    <%= link_to insurance, :class=>"grid-item", :id =>"welcome-grid-item-#{index}" do %>  
      <% if index == 1 %>
        <%= image_tag insurance.image.url(:large), :class=>"img-swap" %>
        <h1><%= insurance.title %></h1>
        <p><%= insurance.link %></p>
      <% elsif index == 3 %>
        <%= image_tag insurance.image.url(:large), :class=>"img-swap" %>
        <h1><%= insurance.title %></h1>
        <p><%= insurance.link %></p>
      <% else %>
        <h1><%= insurance.title %></h1>
        <p><%= insurance.link %></p>
      <% end %>
    <% end %>
  <% end %>  
  <%= link_to quotes_path, :class=>"grid-item grid-item-big", :id => "welcome-grid-item-big" do %>
    <h1>Give us a try and see the difference.</h1>
    <p>Our objective is to make the process as simple as possible. <i class="icon-right-open-mini"></i></p>    
  <% end %>
</div>

app/views/welcome/_hero.html.erb
<div class="image-gradient-dynamic">
  <%= image_tag "bg/hp.jpg" %>
  <div class="overlay"></div>
  <div class="copy">
	<h2>Play More. Worry Less.</h2>
    <p>Home, Auto, and Life Insurance</p>
    <%= link_to "Get Started", quotes_path, class: "btn btn--brand-blue" %>
			<i class="icon-right-open-mini button-icon button-icon--white"></i>
  </div>
</div>

app/views/welcome/_main_content.html.erb
<%= render "hero" %>
<div id="about-box">
	<div class="wrapper">
		<div class="about-box-wrapper animated bounce fadeIn fadeInLeft">
			<h2>
				We’re a <strong>different </strong>kind of insurance brokerage.
			</h2>
			<p>Being able to safely protect your home or auto should be a priority in protecting your investment. Having the right CA insurance agents that can give you valuable advice on auto insurance and home insurance is important.</p><p> Knowing the many options available to you by using an independent agency like Balboa Pacific and their online platform to research and see home and auto insurance quotes from top carriers will give you a head start in making smart selections to meet your needs and your budget.</p>
		</div>
	</div>
</div>
<%= render "grid_objects" %>
<div class="slide-section">
	<div class="wrapper">
		<div class="slider">
		  <div class="slide slide1">
		  	<h3>As a first time home buyer I never had to worry or think about home owners insurance. While in escrow Balboa Pacific was recommended to me and I couldn’t be happier with their service. They were extremely helpful throughout the process. They were able to bundle my auto and home all in one. I was pleasantly surprised with their affordability and knowledge. </h3>
		  	<p>Robert Tuazon </p>
		  </div>
		  <div class="slide slide2">
		  	<h3>I had been using AAA insurance for a few years and they were unwilling to renew my home owners insurance. I turned to Balboa Pacific and they broke down why AAA wasn’t renewing my policy and helped pinpoint the best policy for my situation. I was extremely impressed with the transparency and swiftness of their team. </h3>
		  	<p>Chay Ung</p>
		  </div>
		  <div class="slide slide3">
		  	<h3>Balboa Pacific has wonderful customer service. When I was in an auto accident they were very responsive and helpful. I had a lot of questions and they were there to answer all of them. I was really concerned about being at fault for the accident but they were able to get all of the facts straight and all parties involved were responsible for their own actions. </h3>
		  	<p>Nathan Schmidt</p>
		  </div>
		  <div class="slide slide4">
		  	<h3>Balboa Pacific has been a great company for my car insurance needs. When someone rear-ended me, they were prompt with responding and assisted to make sure I had everything I needed. They were very communicative and immediate with their answers to any number of questions I had.</h3>
		  	<p>Viva Helberg</p>
		  </div>
		</div>
	</div>
</div>	
<section class="wrapper logo-section">
	<h3 class="centered-headline--gray">We connect you to the best service for your needs– Nothing more, nothing less.</h3>
	<ul id="insurance-logo-group">
		<li class="js-fadeInElement fade-in-element"><a href=""><%= image_tag "insurance_logos/logo_01.png" %></a></li>
		<li class="js-fadeInElement fade-in-element"><a href=""><%= image_tag "insurance_logos/logo_02.png" %></a></li>
		<li class="js-fadeInElement fade-in-element"><a href=""><%= image_tag "insurance_logos/logo_03.png" %></a></li>
		<li class="js-fadeInElement fade-in-element"><a href=""><%= image_tag "insurance_logos/logo_04.png" %></a></li>
		<li class="js-fadeInElement fade-in-element"><a href=""><%= image_tag "insurance_logos/logo_05.png" %></a></li>
	</ul>
</section>

<div class="box-services">
	<div class="wrapper">
		<div class="icon"><%= image_tag "svg/piggy.png" %></div>
		<div class="point"><h4>Cost</h4> <p>We save people money. Research shows that broker pricing is generally better than going direct. It’s simple, if we can’t save you money, there is no reason for you to change.</p></div>
		<div class="icon"><%= image_tag "svg/ease.png" %></div>
		<div class="point"><h4>Ease</h4> <p> We make the entire process super easy. You give us your basic info, we find the best policies with the best carriers that match your needs. We do all of the legwork!</p></div>
	</div>
	<div class="wrapper">
		<div class="icon"><%= image_tag "svg/speed.png" %></div>
		<div class="point"><h4>Speed</h4> <p>Time is money.  Save yourself hours and hours of time calling on multiple insurance carriers about multiple types of insurance. We do the insurance thing and do it well with the best carriers.</p></div>
		<div class="icon"><%= image_tag "svg/pencil.png" %></div>
		<div class="point"><h4>Peace of Mind</h4> <p> We make sure that every I is dotted and t is crossed. You will be expertly covered for any unforeseeable circumstances.</p></div>
	</div>
</div>
<!-- <%= render "quotes" %> -->

app/views/welcome/_map.html.erb
<div id="map_canvas"></div>

app/views/welcome/_quotes.html.erb
<div class="cards wrapper">
  <div class="card">
    <div class="card-image">
      <%= image_tag("bg/car_quote.jpg", :alt => "insurance") %>
    </div>
    <div class="card-copy">
      <p>Now I'll be able to save over $500 per year on Auto alone!</p>
      <span>Susan R.</span>
    </div>
  </div>

  <div class="card">
    <div class="card-image">
      <%= image_tag("bg/home_quote.jpg", :alt => "insurance") %>
    </div>
    <div class="card-copy">
      <p>I'm saving $1200/yr on auto and homeowners insurance.</p>
      <span>Kristie B.</span>
    </div>
  </div>

  <div class="card">
    <div class="card-image">
      <%= image_tag("bg/misc_quote.jpg", :alt => "insurance") %>
    </div>
    <div class="card-copy">
      <p>Joe is always there when I need questions answered.</p>
      <span>James B.</span>
    </div>
  </div>
</div>

app/views/welcome/_sidebar.html.erb
	<aside class ="sidebar">
		<div class="cards">
		<% @posts.each do |post| %>
			  <div class="card">
			  	<div class="card-image">
	      		<%= image_tag post.image.url(:medium) %>
	   			</div>
	   			<div class="card-header">
						<%= post.title %>
					</div>
					<div class="card-copy">
			      <p>
							<%= truncate(post.content, :length => 135) %>
						</p>
						<%= link_to "Read More", post %>
					</div>
				</div>
			<% end %>
		</div>
	</aside>

app/views/welcome/index.html.erb
<%= render "hero" %>
<div class="wrapper">
	<section class="intro">
		<aside>
			<h2>
				Insurance you can trust. Savings you will feel.
			</h2>
		</aside>
		<article>
			<p>
				Balboa Pacific offers a broad range of personal and commercial insurance products and options.  We combine decades of experience and stay up to date on the current laws and regulations to deliver the best and most affordable insurance coverage for individuals, families, and businesses of any size.
			</p>
			<p>
				We got you covered, whether you need protection for your company, your employees, your home and valuables, the people you love or all of the above. If you think you are paying too high, you probably are. Our customers save time and money and get peace of mind that they are well covered.
			</p>
			<p>
				Think you might be paying too much? <%= link_to "Contact Us", new_contact_path, :class => current_class?(new_contact_path) %> to find out.
			</p>
		</article>
	</section>
	<section class="insurance-type-slide">
		<article class="insurance-type-slide--wrapper">	
			<div class="owl-carousel image-gradient-dynamic" id="insurance-slider">
				<% @insurance_grid.each_with_index do |insurance, index| %>
				    <div class="insurance-type-slide--content">
				    	<%= link_to insurance, :class=>"", :id =>"#{index}" do %> 
				    		<div class="copy"><h2><%= insurance.title %></h2></div>
							<%= image_tag insurance.image.url(:large), :class=>"img-swap" %>
				        <% end %>
			        </div>
			    <% end %>
			</div>
		</article>
		<aside>
			<h2>
				A wide range of coverage  in one  place.
			</h2>
		</aside>
	</section>
	<section class="customer-quotes">
		<aside>
			<h2>
				Latest Reviews
			</h2>
		</aside>
		<article>
			<div class="owl-carousel image-gradient-dynamic" id="quote-slider">
				<div>
				<p>
					As a first time home buyer I never had to worry or think about home owners insurance. While in escrow Balboa Pacific was recommended to me and I couldn’t be happier with their service. They were extremely helpful throughout the process. They were able to bundle my auto and home all in one. I was pleasantly surprised with their affordability and knowledge.
					<small class="quote-author">Robert Tuazon</small>
				</p>
				</div>
				<div>
				<p>
					I had been using AAA insurance for a few years and they were unwilling to renew my home owners insurance. I turned to Balboa Pacific and they broke down why AAA wasn’t renewing my policy and helped pinpoint the best policy for my situation. I was extremely impressed with the transparency and swiftness of their team.
					<small class="quote-author">Chay Ung</small>
				</p>
				</div>
				<div>
				<p>
					Balboa Pacific has wonderful customer service. When I was in an auto accident they were very responsive and helpful. I had a lot of questions and they were there to answer all of them. I was really concerned about being at fault for the accident but they were able to get all of the facts straight and all parties involved were responsible for their own actions.
					<small class="quote-author">Nathan Schmidt</small>
				</p>
				</div>
				<div>
				<p>
					Balboa Pacific has been a great company for my car insurance needs. When someone rear-ended me, they were prompt with responding and assisted to make sure I had everything I needed. They were very communicative and immediate with their answers to any number of questions I had.
					<small class="quote-author">Viva Helberg</small>
				</p>
				</div>
			</div>
		</article>
	</section>
	<section class="logo-section">
<!-- 		<h3 class="centered-headline--gray">We connect you to the best service for your needs– Nothing more, nothing less.</h3> -->
		<ul id="insurance-logo-group">
			<li class=""><a href=""><%= image_tag "insurance_logos/logo_01.png" %></a></li>
			<li class=""><a href=""><%= image_tag "insurance_logos/logo_02.png" %></a></li>
			<li class=""><a href=""><%= image_tag "insurance_logos/logo_03.png" %></a></li>
			<li class=""><a href=""><%= image_tag "insurance_logos/logo_04.png" %></a></li>
			<li class=""><a href=""><%= image_tag "insurance_logos/logo_05.png" %></a></li>
		</ul>
	</section>
	<p>.</p>
</div>
<script>
	$(".owl-carousel").owlCarousel({
		items: 1
	});
</script>