config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :insurances
  resources :contacts, only: [:new, :create]
  resources :about, only: [:index]
  resources :customer_service

  resources :quotes, only: [:index, :create]
  namespace :insurance_leads do
    resources :current_auto_insurance_policies, only: [:show]
    resources :current_home_insurance_policies, only: [:show]
  end
  get 'welcome/index'
  root 'welcome#index'

  get '*path' => redirect('/')
end

app/models/customer_service.rb
class CustomerService < ActiveRecord::Base
	extend FriendlyId
  friendly_id :name, use: :slugged

  has_attached_file :logo, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
end

app/controllers/customer_service_controller.rb
class CustomerServiceController < ApplicationController

	before_action :find_customerService, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@customerServices = CustomerService.all.order("created_at desc")
	end

	def new
		@customerService = CustomerService.new
	end
		
	def create
		@customerService = CustomerService.new cs_params

		if @customerService.save
			redirect_to customer_service_index_path, notice: "Success."
		else
			render 'new'
		end
	end

	def show
		@customerServices = CustomerService.all.order("created_at desc")
	end

	def edit
	end

	def update
		if @customerService.update(cs_params)
			redirect_to customer_service_index_path, notice: "Success."
		else
			render 'edit'
		end
	end

	def destroy
		@customerService.destroy
		redirect_to customer_service_index_path
	end
	
	private

	def cs_params
		params.require(:customerService).permit(:name, :phone, :site, :logo, :slug)
	end

	def find_customerService
		@customerService = CustomerService.friendly.find(params[:id])
	end

end

app/helpers/customer_service_helper.rb
module CustomerServiceHelper
  def tel_to(number, name = nil, html_options = nil)
    link_to(h(name || number), "tel:#{h(number)}", html_options) if number.present?
  end
end

app/views/customer_service/_form.html.erb
<div class="form">
	<%= form_for :customerService, url: customer_service_index_path do |f| %>
		<%= f.label :logo %>
		<%= f.file_field :logo %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.label :phone %>
		<%= f.telephone_field :phone, id: 'phone', "data-inputmask": "'mask': '999-999-9999'"  %>
		<%= f.label :site %>
		<p>Do not include www: just sitename.com.</p>
		<%= f.text_field :site %>
		<%= f.submit 'Save', class: "button" %>
	<% end %>
</div>

app/views/customer_service/_hero_cs.html.erb
<div class="image-gradient-dynamic">
	<%= image_tag("bg/smiling-coworkers.png", :alt => "Smiling Co-Workers") %>
  <div class="overlay"></div>
  <div class="copy">
    <h2>Need help regarding <br /><span class ="yellow-text">your policy?</span>
    <span class="sub-header">Here's a list of the insurance companies we work with.</span>
</h2>
  </div>
</div>

app/views/customer_service/edit.html.erb
<article class="type-system-serif">
	<section class="wrapper">
		<h1 id="form_title">Edit Insurance Carrier</h1>
		<%= render 'form' %>
	</section>
</article>

app/views/customer_service/index.html.erb
<%= render "hero_cs" %>
<article class="wrapper">
	<section>
		<table class="tables content_well">
		  <thead>
		    <tr>
		      <th>Logo</th>
		      <th>Company Name</th>
		      <th>Company Phone</th>
		      <th>Company Website</th>
					<% if user_signed_in? %>
						<th>Tools</th>
					<% end %>
		    </tr>
		  </thead>
		  <tbody>
		    <% @customerServices.each do |customerService| %>
			    <tr>
			      <td><%= image_tag customerService.logo.url(:large) %></td>
			      <td>
				      <h2><%= customerService.name %></h2>
				    </td>
			      <td>
			      	<%= tel_to(customerService.phone, name = nil, html_options = { :class=>"icon-phone"}) %>
			      </td>
			      <td>
			      	<%= link_to "http://www.#{customerService.site} ", :target=>"_blank", :class=>"button button-yellow-btn" do %>
								Visit Site
			      	<%end%>
			      	<i class="icon-right-open-mini button-icon"></i>
			      </td>
						<% if user_signed_in? %>
							<td>
								<%= link_to "Edit", edit_customer_service_path(customerService) %>
								<%= link_to "Delete", customer_service_path(customerService), method: :delete, data: { confirm: "Are you sure?" } %>
							</td>
						<% end %>
			    </tr>
				<% end %>
		  </tbody>
		</table>
	</section>
</article>

app/views/customer_service/new.html.erb
<article class="type-system-serif">
	<section class="wrapper">
		<h1 id="form_title">New Insurance Carrier</h1>
		<%= render 'form' %>
	</section>
</article>

app/views/customer_service/show.html.erb
<%= render "hero2" %>
<article class="content_well type-system-serif">
	<section class="main">
		<div class="skinny_wrapper--article">
			<%= image_tag @customerService.logo.url(:large) %>
 			<h1 class="hello"><%= @customerService.name %></h1>
 			<h1 class="hello"><%= @customerService.phone %></h1>
 			<h1 class="hello"><%= @customerService.site %></h1>
		</div>
		<div id="admin_links">
			<% if user_signed_in? %>
				<%= link_to "Edit", edit_customer_service_path(@customerService) %>
				<%= link_to "Delete", customer_service_path(@customerService), method: :delete, data: { confirm: "Are you sure?" } %>
			<% end %>
		</div>
	</section>
</article>